### ISSUE TITLE
Uncaught TypeError: Object(...) is not a function

### ISSUE THREAD

**Issue by JarvanQ** [kolkov/ngx-dadata#63]
Не удаётся подключить модуль NgxDadataModule. Сразу получаю ошибку вне зависимости от того, какую версию пакета ngx-dadata устанавливаю в свой проект на ангуларе. 

kolkov-ngx-dadata.js:72 Uncaught TypeError: Object(...) is not a function
    at kolkov-ngx-dadata.js:72:77
    at ./node_modules/@kolkov/ngx-dadata/fesm5/kolkov-ngx-dadata.js (kolkov-ngx-dadata.js:74:2)
    at __webpack_require__ (bootstrap:83:1)
    at ./src/app/shared/shared.module.ts (shared.module.ts:61:1)
    at __webpack_require__ (bootstrap:83:1)
    at ./src/app/app.module.ts (app.module.ts:47:1)
    at __webpack_require__ (bootstrap:83:1)
    at ./src/main.ts (main.ts:4:1)
    at __webpack_require__ (bootstrap:83:1)
    at 0 (main.ts:12:37)
(anonymous) @ kolkov-ngx-dadata.js:72
./node_modules/@kolkov/ngx-dadata/fesm5/kolkov-ngx-dadata.js @ kolkov-ngx-dadata.js:74
__webpack_require__ @ bootstrap:83
./src/app/shared/shared.module.ts @ shared.module.ts:61
__webpack_require__ @ bootstrap:83
./src/app/app.module.ts @ app.module.ts:47
__webpack_require__ @ bootstrap:83
./src/main.ts @ main.ts:4
__webpack_require__ @ bootstrap:83
0 @ main.ts:12
__webpack_require__ @ bootstrap:83
checkDeferredModules @ bootstrap:45
webpackJsonpCallback @ bootstrap:32
(anonymous) @ main.js:1
client:148 [WDS] Warnings while compiling.
warnings @ client:148
onmessage @ socket.js:41
EventTarget.dispatchEvent @ sockjs.js:170
(anonymous) @ sockjs.js:887
SockJS._transportMessage @ sockjs.js:885
EventEmitter.emit @ sockjs.js:86
WebSocketTransport.ws.onmessage @ sockjs.js:2961
wrapFn @ zone.js:1332
push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask @ zone.js:423
push../node_modules/zone.js/dist/zone.js.Zone.runTask @ zone.js:195
push../node_modules/zone.js/dist/zone.js.ZoneTask.invokeTask @ zone.js:498
invokeTask @ zone.js:1744
globalZoneAwareCallback @ zone.js:1770
client:154 ./node_modules/@kolkov/ngx-dadata/fesm5/kolkov-ngx-dadata.js 72:58-76
"export 'ɵɵdefineInjectable' was not found in '@angular/core'
warnings @ client:154
onmessage @ socket.js:41
EventTarget.dispatchEvent @ sockjs.js:170
(anonymous) @ sockjs.js:887
SockJS._transportMessage @ sockjs.js:885
EventEmitter.emit @ sockjs.js:86
WebSocketTransport.ws.onmessage @ sockjs.js:2961
wrapFn @ zone.js:1332
push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask @ zone.js:423
push../node_modules/zone.js/dist/zone.js.Zone.runTask @ zone.js:195
push../node_modules/zone.js/dist/zone.js.ZoneTask.invokeTask @ zone.js:498
invokeTask @ zone.js:1744
globalZoneAwareCallback @ zone.js:1770
client:154 ./node_modules/@kolkov/ngx-dadata/fesm5/kolkov-ngx-dadata.js 72:154-162
"export 'ɵɵinject' was not found in '@angular/core'
warnings @ client:154
onmessage @ socket.js:41
EventTarget.dispatchEvent @ sockjs.js:170
(anonymous) @ sockjs.js:887
SockJS._transportMessage @ sockjs.js:885
EventEmitter.emit @ sockjs.js:86
WebSocketTransport.ws.onmessage @ sockjs.js:2961
wrapFn @ zone.js:1332
push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask @ zone.js:423
push../node_modules/zone.js/dist/zone.js.Zone.runTask @ zone.js:195
push../node_modules/zone.js/dist/zone.js.ZoneTask.invokeTask @ zone.js:498
invokeTask @ zone.js:1744
globalZoneAwareCallback @ zone.js:1770
client:154 ./node_modules/ngx-web-worker/node_modules/@angular/core/fesm5/core.js 27316:15-36
Critical dependency: the request of a dependency is an expression
warnings @ client:154
onmessage @ socket.js:41
EventTarget.dispatchEvent @ sockjs.js:170
(anonymous) @ sockjs.js:887
SockJS._transportMessage @ sockjs.js:885
EventEmitter.emit @ sockjs.js:86
WebSocketTransport.ws.onmessage @ sockjs.js:2961
wrapFn @ zone.js:1332
push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask @ zone.js:423
push../node_modules/zone.js/dist/zone.js.Zone.runTask @ zone.js:195
push../node_modules/zone.js/dist/zone.js.ZoneTask.invokeTask @ zone.js:498
invokeTask @ zone.js:1744
globalZoneAwareCallback @ zone.js:1770
client:154 ./node_modules/ngx-web-worker/node_modules/@angular/core/fesm5/core.js 27328:15-102
Critical dependency: the request of a dependency is an expression

 /** @nocollapse */ NgxDadataService.ngInjectableDef = ɵɵdefineInjectable({ factory: function NgxDadataService_Factory() { return new NgxDadataService(ɵɵinject(HttpClient)); }, token: NgxDadataService, providedIn: "root" });

Мои пакеты
"dependencies": {
    "@angular/animations": "~7.2.0",
    "@angular/cdk": "~7.3.0",
    "@angular/common": "~7.2.0",
    "@angular/compiler": "^7.2.7",
    "@angular/core": "~7.2.0",
    "@angular/flex-layout": "^7.0.0-beta.23",
    "@angular/forms": "~7.2.0",
    "@angular/platform-browser": "~7.2.0",
    "@angular/platform-browser-dynamic": "~7.2.0",
    "@angular/router": "~7.2.0",
    "@aspnet/signalr": "^1.1.4",
    "@aspnet/signalr-protocol-msgpack": "^1.1.0",
    "@asymmetrik/ngx-leaflet": "^5.0.2",
    "@google/markerclusterer": "^1.0.3",
    "@kolkov/ngx-dadata": "^0.4.1",
    "@ngx-translate/core": "^11.0.1",
    "@ngx-translate/http-loader": "^4.0.0",
    "@types/leaflet.markercluster": "^1.4.6",
    "angular-gridster2": "^7.1.0",
    "bootstrap": "^3.4.1",
    "cdk-drag-scroll": "^0.0.2",
    "chart.js": "^2.8.0",
    "chartjs-plugin-annotation": "^0.5.7",
    "chartjs-plugin-crosshair": "^1.1.4",
    "chartjs-plugin-zoom": "^0.7.3",
    "core-js": "^2.5.4",
    "draggable": "^4.2.0",
    "file-saver": "^2.0.5",
    "howler": "^2.1.2",
    "jquery": "^3.6.0",
    "leaflet": "^1.5.1",
    "leaflet.markercluster": "^1.5.3",
    "luxon": "^1.25.0",
    "lzutf8": "^0.6.0",
    "moment": "^2.24.0",
    "ng2-charts": "^2.2.3",
    "ngx-cookie-service": "^2.4.0",
    "ngx-smart-popover": "^1.1.0",
    "ngx-web-worker": "^8.0.0",
    "primeicons": "^1.0.0",
    "primeng": "^7.0.5",
    "rxjs": "~6.3.3",
    "terser": "^3.14.1",
    "tslib": "^1.9.0",
    "tui-image-editor": "^3.5.2",
    "tz-lookup": "^6.1.25",
    "xlsx": "^0.16.9",
    "zone.js": "~0.8.26"
  },

**Comment by kolkov** [comment]
This was a compatibility issue with the v1.x build. v2.0.0 has been completely rewritten as a standalone component with modern Angular Package Format (APF). Please upgrade:

```
npm install @kolkov/ngx-dadata@latest
```

v2.x requires Angular 19+. See [MIGRATION.md](https://github.com/kolkov/ngx-dadata/blob/master/MIGRATION.md).
